version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Table-Formatter"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "table-formatter"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5
